### ISSUE TITLE
uSync should not overwrite template on disk when creating new template

### ISSUE THREAD

**Issue by ScottGuymer** [KevinJump/jumps.umbraco.usync#33]
Use case: using source control to manage source file and web deploy and usync to manage the deployment of doc types and templates to production.

When creating a new template in an environment uSync must not overwrite existing template files that are published from source control regardless of what template is in the def file.

Our designers are updating the file source after the initial creation of the definition and so the definition is not being updated. When republishing a file where the template exists the update works. But on an environment where the template doesn't exist it is creation the template from the (old) definition and overwriting the template published from source.

Its making our deployments a little flaky as we need to make sure we dump the latest template into the uSync def file before it is published to a new environment. failure to do this results in an old template being published.

I would be happy to help implement this as an option or switch if possible.

**Comment by ScottGuymer** [comment]
After a little investigation I now realise that the save is handled by the umbraco framework. The template xml is simply handed off to it and it overwrites the file on the disk.

Not sure what there is in terms of a workaround....

**Comment by KevinJump** [comment]
yeah, 

There isn't actually very much to the umbraco import routine for templates - so it's probibly reasonably safe just to use the FileServices to directly create the template on first use - the only real trick is working out if it's a masterpage or a mvc view - which the code does by looking in the template file for key things like layout. 

I might have a look around.

**Comment by ScottGuymer** [comment]
Yeah i have spent the afternoon looking at it and came to the conclusion i
would have to extract some of the code from the package service and put it
into SyncTemplate.

Does that sound like a good approach?

**Comment by KevinJump** [comment]
I've done it before, lots of the DataType sync stuff was taken out of the package service, the only real risk is you get quite far down the line and then discover that some critical part is marked internal or readonly - then you end up back tracking.

**Comment by KevinJump** [comment]
Fixed this in latest commit - 
uSync now checks and if the content is on the disk, then it doesn't do a PackageService import,

if the template exists, it just updates master and name (alias will have to wait for better renaming support). 

if the template doesn't exist, it creates it but uses the content from the file on disk to create it 

so the disk .cshtml & .master files will always win.

**Comment by ScottGuymer** [comment]
This is great news. After the initial look at how to do it i didnt get round to actually making the changes.

Will i have to built the project myself or will the update be available on nuget?

**Comment by KevinJump** [comment]
Hi it's now in 2.4.10 .so the latest nuget package has it in.
