### ISSUE TITLE
Can't save dictionary items

### ISSUE THREAD

**Issue by jbreuer** [KevinJump/jumps.umbraco.usync#44]
When I try to save a dictionary item I get the following error:

```
[NullReferenceException: Object reference not set to an instance of an object.]
   Umbraco.Core.Strings.DefaultShortStringHelper.InitializeLegacyUrlReplaceCharacters() +32
   jumps.umbraco.usync.SyncDictionary.SaveToDisk(DictionaryItem item) +44
   umbraco.cms.businesslogic.DictionaryItem.Save() +34
   umbraco.settings.EditDictionaryItem.save_Click(Object sender, EventArgs e) +205
   System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument) +152
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +3803
```

I'm using Umbraco 7.3-beta3 and uSync 2.4.10. I know that there a new version for Umbraco 7.3, but I didn't have time yet to test that and it says that this version will probably also still work.

**Comment by KevinJump** [comment]
Think i've fixed it in  24d98b1f0c0d1dbab500b88c7ea4f5f526bcef2c 

Switched from the DefaultStringHandler stuff to the SafeFileName extension, seems to be working 

Haven't tested this pre v7.3 yet - but it should work. 

updated dll if you desperate is in https://github.com/KevinJump/jumps.umbraco.usync/tree/v2.2-Umbraco-7/Package/uSync
