### ISSUE TITLE
UAAS - Trying it out

### ISSUE THREAD

**Issue by emmagarland** [KevinJump/jumps.umbraco.usync#55]
![image](https://cloud.githubusercontent.com/assets/1649855/12702147/23185f3a-c817-11e5-9412-578d5fb8385a.png)

Hi Kevin

I'm aware USync is currently showing as untested on UAAS, but I'm trying it out today (as it is one of my default package installs), and thought I'd let you know of a issue.

The version is uSync.BackOffice, Package version 3.0.4

I'm seeing this issue in the USync backoffice after a trial install of UAAS. When I pull the website down locally, UAAS loads the USync backoffice dashboard fine, exports and so on as expected. However on my Dev and Live USync environments, the back-office shows the attached error. This occurs even when restarting the environments.

I tried installing the package locally via nuget and uploading to UAAS and deploying to dev, but to no avail. (NB the nuget package didn't update the installedpackages.config file so I had to download manually and then manually update the dashboard.config). The package does then show as installed in Umbraco packages but it is still showing the error attached.

I tried to install again over the top of the package but it didn't fix the error.

I do see the warning "This package references the assembly 'Archetype' which was not found". I installed this but still got the same issue.

Any ideas?

Thanks

Emma

**Comment by KevinJump** [comment]
Hi

uSync doesn't work on UaaS : ( 

UaaS uses its own system for keeping the different sites -dev/stage/live- in sync (UmbracoDeploy i think), this does many of the same things that uSync does in terms of tracking and applying changes between different versions of umbraco. Running uSync on top of that would just cause loads of confusion with things being changed, and tracked by both.

To prevent that happening uSync actually [has a line of code in it](https://github.com/KevinJump/uSync/blob/master/Jumoo.uSync.BackOffice/uSyncApplicationEventHandler.cs#L25) to try to stop it running on uSync. 
if you look in the logs you might see "uSync doesn't run on UaaS, so it will just stop now" 

unfortunately I don't think there is a way to tell you that on the package install screen :( 

I haven't had a chance yet to actually check any of this on UaaS - so wasn't aware the dashboard crashed, that should probably just put a message up to 

The archetype message is ok (i need to put something up about that) usync has an element to sync archetype values should you have them, but its not referenced unless you have archetype installed, Unfortunately the package installer is being clever and notices the reference so gives you a warning

**Comment by emmagarland** [comment]
That makes sense, thanks Kevin for the detailed reply - it is good to know this officially.

Emma

**Comment by martinmoresco** [comment]
Hi Kevin,

I have an Umbraco installation and I'm trying to use usync to move the changes I'm doing in a DEV instance to the rest of environments (stg and production). When I'm installing the uSync.ContentEdition package I'm getting this error

**Binary file errors detected
Read more...
This package contains .NET binary files that might not be compatible with this version of Umbraco. If you aren't sure what these errors mean or why they are listed please contact the package creator.

Error report
This package references the assembly 'Archetype' which was not found**

If I ignore it and install it anyway I get this other message

**The given path's format is not supported.**

Can you help me with this?

Thanks 
.martin

**Comment by martinmoresco** [comment]
Full Error Message is 

Server Error in '/' Application.

The given path's format is not supported.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NotSupportedException: The given path's format is not supported.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 


[NotSupportedException: The given path's format is not supported.]
   System.Security.Util.StringExpressionSet.CanonicalizePath(String path, Boolean needFullPath) +14633709
   System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath) +351
   System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList) +151
   System.IO.Path.GetFullPath(String path) +175
   Umbraco.Core.IO.PhysicalFileSystem.GetFullPath(String path) +172
   Umbraco.Web.MediaPropertyExtensions.PopulateFileMetaDataProperties(IContentBase content, IImagingAutoFillUploadField uploadFieldConfigNode, String relativeFilePath) +167
   Umbraco.Web.PropertyEditors.FileUploadPropertyEditor.AutoFillProperties(IContentBase model) +446
   Umbraco.Web.PropertyEditors.FileUploadPropertyEditor.MediaServiceSaving(IMediaService sender, SaveEventArgs`1 e) +73
   Umbraco.Core.Events.TypedEventHandler`2.Invoke(TSender sender, TEventArgs e) +0
   Umbraco.Core.Services.MediaService.Umbraco.Core.Services.IMediaServiceOperations.Save(IMedia media, Int32 userId, Boolean raiseEvents) +176
   Umbraco.Core.Services.MediaService.Save(IMedia media, Int32 userId, Boolean raiseEvents) +51
   Jumoo.uSync.Core.Serializers.MediaSerializer.DeserializeCore(XElement node, Int32 parentId, Boolean forceUpdate) +1534
   Jumoo.uSync.Content.MediaHandler.Import(String file, Int32 parentId, Boolean force) +414
   Jumoo.uSync.Content.BaseContentHandler`1.ImportFolder(String folder, Int32 parentId, Boolean force, Dictionary`2 updates) +920
   Jumoo.uSync.Content.BaseContentHandler`1.ImportFolder(String folder, Int32 parentId, Boolean force, Dictionary`2 updates) +1959
   Jumoo.uSync.Content.BaseContentHandler`1.ImportAll(String folder, Boolean force) +431
   Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(String groupName, String folder, Boolean force) +1221
   Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup() +387

[ApplicationException: uSync encounted an error during setup (which is probibily from an import)
     You can set DontThrowErrors = True in the uSyncBackOffice.Config file and umbraco will not throw the YSOD (usync will just log errors in the log file)]
   Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup() +1467
   Umbraco.Core.CoreBootManager.<Complete>b__a(IApplicationEventHandler x) +381
   Umbraco.Core.EnumerableExtensions.ForEach(IEnumerable`1 items, Action`1 action) +148
   Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete) +320
   Umbraco.Web.WebBootManager.Complete(Action`1 afterComplete) +189
   Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e) +355

[HttpException (0x80004005): uSync encounted an error during setup (which is probibily from an import)
     You can set DontThrowErrors = True in the uSyncBackOffice.Config file and umbraco will not throw the YSOD (usync will just log errors in the log file)]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +12964021
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +175
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +304
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +404
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +475

[HttpException (0x80004005): uSync encounted an error during setup (which is probibily from an import)
     You can set DontThrowErrors = True in the uSyncBackOffice.Config file and umbraco will not throw the YSOD (usync will just log errors in the log file)]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +12981028
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +12820621

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34280

**Comment by KevinJump** [comment]
Hi martin, 

first the easy bit, you can ignore he binary error, it is because content edition contains a mapper for Archetype which if needed calls the archetype code, but unless you have archetype installed it is never called so you can install and ignore :) 

the path issue is slighty more complex - it sounds a lot like a rouge character in the path - content edition use the name of the node as part of the file path, but this is passed through the internal umbraco `ToSafeFileName` functions - sounds like they might not be that safe :( 

if you could look on the disk, you hopefully have a partial export of content (until the failure) and that might pin point where abouts the rouge node is. - if you can work out from that what teh next node to be exported would have been we might be able to pinpoint the issue.

another option is to turn on the debug logging in log4net.confg

` <logger name="Jumoo.uSync"><level value="Debug"/></logger>`

then you will get lots of logging and it will hopefully show us what usync was doing just before the error

**Comment by martinmoresco** [comment]
Thanks so much Kevin.

I-ll try this and will let you know.


Best

2016-10-21 5:28 GMT-03:00 Kevin Jump <notifications@github.com>:

**Comment by martinmoresco** [comment]
Hi Kevin

Just to be sure. In order to use Usync I must click on the export button,
then copy the files/folders under ~usync\data from the source server to the
target server ~usync\data folder and just then click on the import button
in the target server. Am I right?

Best

2016-10-21 5:28 GMT-03:00 Kevin Jump <notifications@github.com>:

**Comment by KevinJump** [comment]
Hi, 

you can mange things with the import / export buttons, but out of the box usync will actually do most of that automatically.

if `ExportOnSave` is set to true in the usyncbackoffice.config file: 

Everytime you save something in the umbrao backoffice, usync will write the file out to the usync/data folder. 

if `Import = true` in the target site:
then if you copy that folder over, then on application start (or the import button) then usync will process the files and apply the changes to your target umbraco site.

**Comment by martinmoresco** [comment]
Thanks!

2016-10-27 14:56 GMT-03:00 Kevin Jump <notifications@github.com>:
