### ISSUE TITLE
uSync 3.1.2.740

### ISSUE THREAD

**Issue by aDotNetDeveloper** [KevinJump/jumps.umbraco.usync#58]
Hi Kevin,

Just upgraded to 3.2.740

so current versions are now;
```
  <package id="uSync" version="3.1.2.740" targetFramework="net452" />
  <package id="uSync.ContentEdition" version="3.1.0.740" targetFramework="net452" />
  <package id="uSync.Core" version="5.3.3.740" targetFramework="net452" />
```

uSyncCore.config seemed to be missing most of the settings, so I used the original from 3.1.1.740

This error occurs with or without movemedia as true, both on full import and export
```
Error: An error has occurred. - Method not found: 'Jumoo.uSync.Core.Interfaces.ISyncFileHandler`1<Umbraco.Core.Models.IMedia> Jumoo.uSync.Core.uSyncCoreContext.get_MediaFileMover()'
```

The result is that the media folders and items are created, no images are added though

regards
Wayne

**Comment by KevinJump** [comment]
yeah, my fault i didn't push out the update to content edition as part of the release :disappointed: 

ContentEdition 3.1.1 should be on nuget now.
