### ISSUE TITLE
Images not importing

### ISSUE THREAD

**Issue by victorcea87** [KevinJump/jumps.umbraco.usync#61]
Hi,

I'm having a lot of problems with the images importing with uSync. I'm doing what Kevin Jump said me, it means put the media importing to false and leaving the images in the root media folder (in the uSync>Data>Media I just have the configs). The problem what I'm having now is that I'm doing a full import and the images are created in the media tab in Umbraco but they are not visible, is very strange, I can see the item in the media tab but when I access the image doesn't appear and the website doesn't charge them neither.

Any thoughts?

Thanks!

**Comment by victorcea87** [comment]
I can see as well that when uSync imports the images a part of the problem that it's importing them in wrong way is changing all the config files from each media in uSync folder to remove the src href to the media folder and leave it empty :( it's frustrating.

**Comment by KevinJump** [comment]
Hi i am moving this to the new repo, just to keep it in the right place. I will answer over there.
