### ISSUE TITLE
Dictionary broken in uSync Core 5.5.0

### ISSUE THREAD

**Issue by AllanKirk** [KevinJump/jumps.umbraco.usync#63]
Dictionary items do not get handled correctly in uSync Core 5.5.0.740
If I create a root dictionary item, it does not get its values saved to disk. If I create a sub-key, it is not included, but the values are saved to the parent.

I have downgraded my project to 5.4.0.740, which solved the problem completely.

**Comment by KevinJump** [comment]
Hi, 

I've moved this to the other uSync repo (this one if for the old v4/v6 version 
https://github.com/KevinJump/uSync/issues/75

(good news is i've fixed it... just repackaging now)

**Comment by KevinJump** [comment]
this is fixed (and released in Core 5.5.1 (and uSync 3.2.1 if you use the package).
